USE [master]
GO

/****** Object:  Database [projecthealthdb]    Script Date: 11/5/2019 11:07:02 PM ******/
DROP DATABASE [projecthealthdb]
GO

/****** Object:  Database [projecthealthdb]    Script Date: 11/5/2019 11:07:02 PM ******/
CREATE DATABASE [projecthealthdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projecthealthdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\projecthealthdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projecthealthdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\projecthealthdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projecthealthdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projecthealthdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projecthealthdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projecthealthdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projecthealthdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projecthealthdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [projecthealthdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projecthealthdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projecthealthdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projecthealthdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projecthealthdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projecthealthdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projecthealthdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projecthealthdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projecthealthdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projecthealthdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projecthealthdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projecthealthdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projecthealthdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projecthealthdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projecthealthdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projecthealthdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projecthealthdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projecthealthdb] SET RECOVERY FULL 
GO

ALTER DATABASE [projecthealthdb] SET  MULTI_USER 
GO

ALTER DATABASE [projecthealthdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projecthealthdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projecthealthdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projecthealthdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projecthealthdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projecthealthdb] SET QUERY_STORE = OFF
GO

USE [projecthealthdb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [projecthealthdb] SET  READ_WRITE 
GO


